disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- line_length
- trailing_newline
- mark
- large_tuple
- comma
- syntactic_sugar
- function_body_length
- cyclomatic_complexity
- file_length
- shorthand_operator
- function_parameter_count
- multiple_closures_with_trailing_closure
- valid_ibinspectable
- type_body_length
- comment_spacing
#- vertical_whitespace


# Enable rules not from the default set.# some rules are only opt-in
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # Find all the available rules by running: `swiftlint rules`
  - empty_string
    
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- Project/Resources/Assets
- Project/Common/Extensions
- Project/Resources/Libraries

# Overrided rules >>>.
empty_count: warning
empty_string: warning

vertical_whitespace:
 max_empty_lines: 5

identifier_name:
#validates_start_with_lowercase: false
 min_length:
  warning: 1
  error: 1

reporter: "xcode"
